[package]
name = "nonogrid"
version = "0.1.0"
authors = ["Ivan Ladelshchikov <tsionyx@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.4"
serde_derive = "1.0.87"
serde = "1.0.87"
log = "*"
env_logger = "*"
priority-queue = "0.5.2"
ordered-float = "1.0"
clap = "2.32.0"
sxd-document = "0.3.0"
sxd-xpath = "0.4.2"
reqwest = "0.9.10"
cached = "0.8.0"
